# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
#
# This file contains the workflows that are run periodically to build the examples.

name: build_project_workflow

on:
  workflow_call: {}
  workflow_dispatch: {}

# -------------------------------------------------------------------------------------------------
jobs:
  # -----------------------------------------------------------------------------------------------
  build:
    name: Build Project
    runs-on: ubuntu-20.04
    container: espressif/idf:latest # <--- Specify version of ESP-IDF in image tag
    strategy:
      fail-fast: false
      matrix:
        espidf_target: ["esp32", "esp32c3", "esp32s2", "esp32s3"]  # <--- Specify a list of Espressif chips connected to your runner
    steps:
      # -------------------------------------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          submodules: 'true'
      # -------------------------------------------------------------------------------------------
      - name: Build Application with ESP-IDF
        env:
          IDF_TARGET: ${{ matrix.espidf_target }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build
      # -------------------------------------------------------------------------------------------
      - name: Upload files to artifacts for run-target job
        uses: actions/upload-artifact@v2
        with:
          name: esp-idf_template_project_ci_bin_${{ matrix.espidf_target }}
          path: |
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/esp-idf_template_project_ci.bin
            build/esp-idf_template_project_ci.elf
            build/flasher_args.json
  # -----------------------------------------------------------------------------------------------
