# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
#
# This file contains the workflows that are run periodically to build the examples.

name: build_project_esp

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
          fail-fast: false
          matrix:
            espidf_target: ["esp32", "esp32c3", "esp32s2", "esp32s3"]  # <--- Specify a list of Espressif chips
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: ${{ matrix.espidf_target }}
    - name: Upload files to artifacts for run-target job
      uses: actions/upload-artifact@v3
      with:
        name: target_${{ matrix.espidf_target }}
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/esp-idf_template_project_ci.bin
          build/esp-idf_template_project_ci.elf
          build/flasher_args.json
        if-no-files-found: error
